### ISSUE TITLE
Confusing typo in the docs

### ISSUE THREAD

**Issue by paulmsmith** [frctl/fractal.build#11]
Hi @allmarkedup 

I'm just getting started with my first opportunity to use Fractal on a real project. Noticed a slight typo/issue in these docs. 

Line 128 or 132 must be incorrect of this file: [08-docs/01-index.md](https://github.com/frctl/fractal.build/blob/master/docs/guide/08-docs/01-index.md). Is it a 'slash' or an 'underscore' that will escape expressions?

My second question, is that true for Nunjucks expressions as well? (assuming so). Not had chance to test yet.

**Comment by allmarkedup** [comment]
Thanks @paulmsmith - will fix that typo up.

As for Nunjucks - no it is not the same. The escaping syntax is template-language specific (i.e. not something that Fractal itself has implemented). For Nunjucks you need to include the text to be printed verbatim within a [`raw` block](https://mozilla.github.io/nunjucks/templating.html#raw) - for example:

``` nunjucks
{% raw %}
{{ foo }}
{% endraw %}
```

**Comment by paulmsmith** [comment]
Ah, `Raw`, of course. Thanks @allmarkedup
