### ISSUE TITLE
Config data stopped working. 

### ISSUE THREAD

**Issue by gward35** [frctl/fractal.build#24]
Hi, I blew away my project and recloned it. When running gulp fractal:build I get the same error for all components

"✘ Error loading data file C:\xampp\htdocs\stsci-frontend\build\src\panini\partials\components\side-nav.config.yml: Cannot read property 'toLowerCase' of undefined"

The configs are on the same level as their html counterparts and they look like:
accordion.config.yml 

context:
    accordion:
      -
        accordion-title: "Collapsed Drawer Tab"
        id: "Test"
        sections:
          -
            section:
              content: "Some Stuff"
etc. 

The build finished and has all the components in the web ui but there is no context data, rendered html, notes

How can I resolve this error this was working before.

**Comment by tlenex** [comment]
looks like you have an syntax error in `side-nav.config.yml`, post here contents of this file.

**Comment by gward35** [comment]
Hi thanks for replying. I want to reiterate that this is happening for
every single component.

FYI, "usage" is a custom tab I added. The data being passes was rendering
fine as well before.

Here is one of the configs:

ad-box.config.yml

context:
    title-intro: "Title Intro"
    title-main: "Title Main"
    image:
      src-small: "mission-1-500.jpg"
      src-large: "mission-1.jpg"
      alt: "image alt text"
    url: "/"
    hover-reveal__revealed:
      data: "<p>Revealed Descriptive Text</p>"
      btn:
        btn-txt: "Learn More"
        btn-url: "/"
      content-section: "content-section-1"

notes:
    >
      <h2>Ad Box</h2>
      <br/>
      <h3>GOALS</h3>
      <p>Highlight sections of content with headlines, images, and more
information revealed upon user interaction</p>
      <br>
      <h3>EXPECTED BEHAVIOR</h3>
      <p>Users should see a display of an image with text centered on top.
On hover (or touch, or focus with a keyboard), more information is revealed
to the user, including a link for more information. When presented in a row
in desktop, the ad boxes should stack vertically in smaller screens.</p>
      <br />
      <h3>DEVELOPMENT NOTES</h3>
      <p>The border color on the bottom of the block and the background
color of the revealed area is controlled with the classes
content-section-1, content-section-2, and content-section-3.  In other
pages of the site, the location of where the page is or type of content
controls the color of some accent areas, including the background color of
blocks similar to the ones on the homepage, the border underneath page
titles, and the background color behind sorting filters.
      <br>Programmatically add these classes to control the colors on these
accent areas:</p>
      <ol>
      <li>Mustard/gold is content-section-1</li>
      <li>Purple is content-section-2</li>
      <li>Blue is content-section-3</li>
      </ol>
      <p>In the front end that agencyQ is providing, each of these ad
blocks (with more content revealed on interaction) uses the same HTML
structure and .less styling. It doesn’t matter if there are three in a row
(as currently pictured on the home page), two, or one—the space of each ad
block is determined with flexbox css and not on any HTML structure. </p>
      <p><b>NOTE:</b> When the revealed content appears in a two-column
layout, different HTML is necessary. See Ad Blocks—Vertical Mobile for more
information.</p>
      <h3>CMS FIELDS / NOTES</h3>
      <ol>
      <li>Content editors need to upload an 1170x400 pixel image</li>
      <li>Editors need to be able to enter text for the headline with a way
to differentiate the thin, intro text from the heavier main text. A style
dropdown in an editor could accomplish this, creating a <code>&lt;span
class="hover-reveal&#95;&#95;title-intro"&gt;</code> and <code>&lt;span
class="hover-reveal&#95;&#95;title-main"&gt;</code></li>
      <li>Rich Text field for the text that is revealed on hover in this
<code>&lt;div class="hover-reveal&#95;&#95;text"&gt;</code></li>
      <li>Content editors should be able to change the text and link
location of the buttons</li>
      </ol>
      <h3>ACCESIBILITY/508 COMPLIANCE</h3>
      <p><code>aria-hidden</code> attributes are toggled with javascript.
<code>tabindex="0"</code> allows users to use the keyboard to focus on the
blocks, and javascript enables slide up/down on keyboard focus/blur.</p>
      <h3>STYLING</h3>
      <p>Styling of these blocks is done with a combination of
<code>_hover-reveal.less</code> and the <code>.text-overlay</code> from
<code>_helpers.less</code>. See “Development Notes” for information about
the border color of the blocks and the background color of the revealed
area.</p>
      <h3>JAVASCRIPT MODULES</h3>
      <p>Interaction for this is handled with
<code>hover-reveal-keyboard.js</code></p>
usage:
    >
      <h2>Ad-Box</h2>
      <ul>
      <li><strong>What:</strong> Ad Box presents as an image with a text
overlay. When a user hovers over this image, more information is revealed.
This can include headlines, images, and a link to more information.</li>
      <li><strong>Why:</strong> This is a method for presenting content
cleanly and concisely. The page isn’t cluttered with too much information;
rather, it is presented visually (as most users prefer to navigate content)
and users are able to see more information when they find an image/text
that interests them. The user is then able to click out to another page to
get more information and see the subject in further depth.</li>
      <li><strong>How:</strong> This might be used for different
telescopes, missions, or discoveries or other news - anything that is
visually appealing and has more information elsewhere on the site. Similar
content can be grouped together (for example, various photos of outer
space) so that the user can see them all at once and click on whichever
they are most interested in.</li>
      <li><strong>Suggested Pages:</strong></li>
      <li><strong>Examples:</strong></li>
      </ul>

**Comment by tlenex** [comment]
`"✘ Error loading data file C:\xampp\htdocs\stsci-frontend\build\src\panini\partials\components\side-nav.config.yml: Cannot read property 'toLowerCase' of undefined"`

Look at the error, it points out an file where error was thrown. There should be an yaml syntax error in `side-nav.config.yml` file, not in `ad-box.config.yml`.

**Comment by gward35** [comment]
It throws that error for every config I am saying. Not just one. I have 123
components that are getting the exact same error all of the sudden with
zero syntax change.

**Comment by gward35** [comment]
My best guess is that in the error toLowerCase is referencing default which
has become undefined for some reason. I have a customer theme which has a
setting "format : 'yaml'" to set the configs is this correct?

**Comment by gward35** [comment]
Morning, additionally I believe this is a paths issue now. When the context
data was working @frctl was in node_modules. I moved it out of node modules
and into a libs folder because I made custom changes and did not want them
blown away at every npm i.

So my folder structure was:

build
  - gulpfile.js
  - node_modules (@frctl in here)
  - src
    - panini
      - partials
        - components
          - component-file.html
          - component.config.yml

it is now:


build
  - gulpfile.js
    - lib (@frctl in here)
  - node_modules
  - src
    - panini
      - partials
        - components
          - component-file.html
          - component.config.yml

when running fractal:build it sends me to the error on line 69 of
@frctl/fractal/src/core/data.js

It cant find the configs, how do I remedy this.

For what its worth setting global context in fractal.js works but it
obviously isnt what I want
